BARTPerks/Controllers/PerksController.cs
using System;
using System.Net;
using System.Web.Mvc;
using Newtonsoft.Json;
using BARTPerks.DAL;
using BARTPerks.Models;

[assembly: log4net.Config.XmlConfigurator(Watch = true)]

namespace BARTPerks.Controllers
{
    public class PerksController : Controller
    {
        public ActionResult RewardParticipation()
        {
            ViewBag.ErrorMessage = "";
            ViewBag.ErrorDetails = "";

            return View();
        }

        [HttpPost]
        public ActionResult RewardParticipation(PerksModel model, string Action)
        {
            ViewBag.Message = "";
            ViewBag.ErrorMessage = "";
            ViewBag.ErrorDetails = "";

            try
            {
                var apiManager = new APIManager();
                var apiResponse = apiManager.ValidateCouponCode(model.CouponCode);

                if (apiResponse.StatusCode.Equals(HttpStatusCode.OK))
                {
                    if (apiResponse.status.Equals("error", StringComparison.CurrentCultureIgnoreCase))
                    {
                        // currently happens when code not found
                        ViewBag.ErrorMessage = apiResponse.error;
                        ViewBag.ErrorDetails = JsonConvert.SerializeObject(apiResponse);
                    }
                    else
                    {
                        if (apiResponse.data.valid)
                        {
                            if (model.CouponCode.Equals("waitlist"))
                            {
                                return View("JoinWaitList", model);
                            }
                            else
                            {
                                return View("UserSignup", model);
                            }
                        }
                        else
                        {
                            ViewBag.ErrorMessage = "Invalid coupon code.";
                            ViewBag.ErrorDetails = JsonConvert.SerializeObject(apiResponse);
                        }
                    }
                }
                else if (apiResponse.StatusCode.Equals(HttpStatusCode.NotFound))
                {
                    ViewBag.ErrorMessage = "Invalid coupon code.";
                    ViewBag.ErrorDetails = JsonConvert.SerializeObject(apiResponse);
                }
                else
                {
                    ViewBag.ErrorMessage = string.Format("Unexpected HttpStatusCode: {0}.", apiResponse.StatusCode);
                    ViewBag.ErrorDetails = JsonConvert.SerializeObject(apiResponse);
                    return View("Error", model);
                }
            }
            catch (Exception ex)
            {
                ViewBag.ErrorMessage = "Exception calling the API.";
                ViewBag.ErrorDetails = string.Format("{0} {1} {2}", ex.Source, ex.Message, ex.StackTrace);
                return View("Error", model);
            }

            return View(model);
        }

        public ActionResult JoinWaitList(PerksModel model)
        {
            if (string.IsNullOrEmpty(model.CouponCode))
            {
                return RedirectToAction("RewardParticipation");
            }

            ViewBag.Message = "";
            ViewBag.ErrorMessage = "";
            ViewBag.ErrorDetails = "";

            return View();
        }

        [HttpPost]
        public ActionResult JoinWaitList(PerksModel model, string Action)
        {
            ViewBag.Message = "";
            ViewBag.ErrorMessage = "";
            ViewBag.ErrorDetails = "";

            try
            {
#if DEBUG
                if (model.EmailAddress == "me@home.com")
                {
                    ViewBag.Message = " you have been added to the waitlist.";
                    return View("ProcessComplete", model);
                }
#endif
                var apiManager = new APIManager();
                var apiResponse = apiManager.JoinWaitList(model.EmailAddress);

                if (apiResponse.StatusCode.Equals(HttpStatusCode.OK))
                {
                    if (apiResponse.status.Equals("error", StringComparison.CurrentCultureIgnoreCase))
                    {
                        ViewBag.ErrorMessage = apiResponse.error;
                        ViewBag.ErrorDetails = JsonConvert.SerializeObject(apiResponse);
                    }
                    else
                    {
                        ViewBag.Message = " you have been added to the waitlist.";
                        return View("ProcessComplete", model);
                    }
                }
                else
                {
                    ViewBag.ErrorMessage = string.Format("Unexpected HttpStatusCode: {0}.", apiResponse.StatusCode);
                    ViewBag.ErrorDetails = JsonConvert.SerializeObject(apiResponse);
                    return View("Error", model);
                }
            }
            catch (Exception ex)
            {
                ViewBag.ErrorMessage = "Exception calling the API.";
                ViewBag.ErrorDetails = string.Format("{0} {1} {2}", ex.Source, ex.Message, ex.StackTrace);
                return View("Error", model);
            }

            return View(model);
        }

        public ActionResult UserSignup()
        {
            ViewBag.Message = "";
            ViewBag.ErrorMessage = "";
            ViewBag.ErrorDetails = "";

            return View();
        }

        [HttpPost]
        public ActionResult UserSignup(PerksModel model, string Action)
        {
            ViewBag.Message = "";
            ViewBag.ErrorMessage = "";
            ViewBag.ErrorDetails = "";

            try
            {
                var apiManager = new APIManager();
                var apiResponse = apiManager.UserSignup(model);

                if (apiResponse.StatusCode.Equals(HttpStatusCode.OK))
                {
                    if (apiResponse.status.Equals("error", StringComparison.CurrentCultureIgnoreCase))
                    {
                        ViewBag.ErrorMessage = apiResponse.description;
                        ViewBag.ErrorDetails = JsonConvert.SerializeObject(apiResponse);
                    }
                    else
                    {
                        ViewBag.Message = " your signup is complete!";
                        return View("ProcessComplete", model);
                    }
                }
                else
                {
                    ViewBag.ErrorMessage = apiResponse.description;
                    ViewBag.ErrorDetails = JsonConvert.SerializeObject(apiResponse);
                }
            }
            catch (Exception ex)
            {
                ViewBag.ErrorMessage = "Exception calling the API.";
                ViewBag.ErrorDetails = string.Format("{0} {1} {2}", ex.Source, ex.Message, ex.StackTrace);
                return View("Error", model);
            }

            return View(model);
        }

        public ActionResult ProcessComplete()
        {
            ViewBag.ErrorMessage = "";
            ViewBag.ErrorDetails = "";

            return View();
        }
    }
}

BARTPerks/Views/Perks/JoinWaitList.cshtml
@model BARTPerks.Models.PerksModel

@{
    ViewBag.Title = "Enrollment Signup";
    ViewBag.BodyClasses = "page-enrollment-sign-up";
}

<div class="title-wrapper clearfix">
    <h1 class="title" id="page-title">@ViewBag.Title</h1>
</div>
<div class="region region-content">
    <div class="enroll-desc">
        <span class="es-closed">BART Perks enrollment is closed</span>
        <p>BART Perks is in private beta right now. If you would like to be notified about future opportunities to participate, sign up here.</p>
        <div id="block-system-main" class="block block-system">
            <div class="content">
                @using (Html.BeginForm("JoinWaitList", "Perks", FormMethod.Post, new { @id = "bart-perk-enrollment-signup-form", enctype = "multipart/form-data", @class = "bart-perk-custom-form" }))
                {
                    @Html.HiddenFor(m => m.CouponCode)
                    <div>
                        <div class="ls-static-bart-content">
                            <div class="ls-content">
                                <img src="~/Content/images/logo_perks.png" alt="BART Logo">
                                <p>
                                    Are you a peak period BART rider in need of some Participation requires a coupon code breathing room? BART Perks gives Clipper Card users occasional rewards to shift to less crowded trains and advises you on less crowded times to travel.
                                    If you sign up, you’ll also be eligible to receive occasional rewards for weekend travel.
                                </p>
                                <p>BART Perks is a test program. Participation is limited and by invitation only. For more information, read the <a href="/Bartperklocal/">FAQs</a></p>
                            </div>
                        </div>
                        <div class="es-container perk-form-right">
                            <div class="form-item form-type-textfield form-item-email">
                                <label class="element-invisible" for="edit-email">Email Address <span class="form-required" title="This field is required.">*</span></label>
                                @Html.TextBoxFor(m => m.EmailAddress, new { @class = "user-email form-text required", id = "edit-email", name = "email", @size = "60", @maxlength = "128", autocomplete = "off", placeholder = "Email Address" })
                                <div class="description">Email Address.</div>
                            </div>
                            <input class="custom-form-submit cus-btn-disabled form-submit" type="submit" id="edit-submit" name="op" value="SIGN-UP" disabled="disabled">
                            <div class="terms-condition">By clicking the Sign Up button, you agree to our <a href="/">Terms &amp; Conditions</a>, and <a href="/">Privacy Policy</a>.</div>
                        </div>
                    </div>
                }
            </div>
        </div>
    </div>
</div>

BARTPerks/Views/Perks/ProcessComplete.cshtml
@model BARTPerks.Models.PerksModel

@{
    ViewBag.Title = "Signup Complete";
    ViewBag.BodyClasses = "page-gift-card page-gift-card-signup";
}

<div class="title-wrapper clearfix">
    <h1 class="title" id="page-title">@ViewBag.Title</h1>
</div>
<div class="region region-content">
    <div id="block-system-main" class="block block-system">
        <div class="content">
            <div class="signup-desc">
                <div class="success-status">
                    <p>Congratulations @ViewBag.Message</p>
                </div>
            </div>
        </div>
    </div>
</div>

BARTPerks/Views/Perks/RewardParticipation.cshtml
@model BARTPerks.Models.PerksModel

@{
    ViewBag.Title = "Welcome";
    ViewBag.BodyClasses = "page-reward-participation";
}

<div class="title-wrapper clearfix">
    <h1 class="title" id="page-title">@ViewBag.Title</h1>
</div>
<div class="region region-content">
    <div class="copon-code-desc">
        <p>Welcome to</p><img src="~/Content/images/logo_perks.png" class="cc-form-bart-logo" alt="BART Logo">
        <p>Get rewarded for riding at less crowded times</p>
        <div id="block-system-main" class="block block-system">
            <div class="content">
                @using (Html.BeginForm("RewardParticipation", "Perks", FormMethod.Post, new { @id = "bart-perk-custom-coupon-code-form", enctype = "multipart/form-data", @class = "bart-perk-custom-form" }))
                {
                    <div>
                        <div class="ls-static-bart-content">
                            <div class="ls-content">
                                <p>
                                    Are you a peak period BART rider in need of some Participation requires a coupon code breathing room? BART Perks gives Clipper Card users occasional rewards to shift to less crowded trains and advises you on less crowded times to travel.
                                    If you sign up, you’ll also be eligible to receive occasional rewards for weekend travel.
                                </p>
                                <p>
                                    BART Perks is a test program. Participation is limited and by invitation only. For more information, read the <a href="/Bartperklocal/">FAQs</a>
                                </p>
                            </div>
                        </div>
                        <div class="cc-container perk-form-right">
                            <p>Participation requires a coupon code</p>
                            <div class="form-item form-type-textfield form-item-coupon-code">
                                <label class="element-invisible" for="edit-coupon-code">Coupon Code <span class="form-required" title="This field is required.">*</span></label>
                                @Html.TextBoxFor(m => m.CouponCode, new { @class = "coupon-code form-text required", id = "edit-coupon-code", name = "coupon_code", @size = "60", @maxlength = "128", autocomplete = "off", placeholder = "Enter Coupon Code" })
                                <div class="description">Coupon Code.</div>
                            </div>
                            <div class="cc-submit">
                                <input class="custom-form-submit cus-btn-disabled form-submit" type="submit" id="edit-submit" name="op" value="SUBMIT" disabled="disabled">
                            </div>
                        </div>
                    </div>
                }
            </div>
        </div>
    </div>
</div>

BARTPerks/Views/Perks/Signup.cshtml
@model BARTPerks.Models.PerksModel

@{
    ViewBag.Title = "Gift Card Signup";
    ViewBag.BodyClasses = "page-gift-card page-gift-card-signup";
}
<style>
    .page-gift-card.page-gift-card-signup .main-content-wrap .gc-wrap .signup-wrap > form {
        display: block !important;
    }
</style>
<div class="title-wrapper clearfix">
    <h1 class="title" id="page-title">@ViewBag.Title</h1>
</div>
<div class="region region-content">
    <div id="block-system-main" class="block block-system">
        <div class="content">
            <div class="signup-desc">
                <div class="success-status">
                    <p>Congratulations!</p>
                </div>
                <p>Fill in the information below to complete your registration and receive your [$X] gift card.</p>
            </div>
            <div class="gc-parent">
                <div class="ls-static-bart-content">
                    <div class="ls-content">
                        <img src="~/Content/images/logo_perks.png" alt="Bart Logo">
                        <p>Are you a peak period BART rider in need of some Participation requires a coupon code breathing room? BART Perks gives Clipper Card users occasional rewards to shift to less crowded trains and advises you on less crowded times to travel. If you sign up, you’ll also be eligible to receive occasional rewards for weekend travel.</p>
                        <p>BART Perks is a test program. Participation is limited and by invitation only. For more information, read the <a href="/Bartperklocal/">FAQs</a></p>
                    </div>
                </div>
                <div class="gc-wrap">
                    <div class="gc-signup-form">
                        <div class="signup-wrap">
                            @using (Html.BeginForm("Signup", "Perks", FormMethod.Post, new { @id = "bart-sso-custom-signup-form", enctype = "multipart/form-data", @class = "bart-perk-custom-form" }))
                            {
                                @Html.HiddenFor(m => m.CouponCode)
                                <div>
                                    <div class="gift-card-container">
                                        <div class="form-item form-type-textfield form-item-first-name">
                                            <label class="element-invisible" for="edit-first-name">First Name <span class="form-required" title="This field is required.">*</span></label>
                                            @Html.TextBoxFor(m => m.FirstName, new { @class = "user-first-name form-text required", id = "edit-first-name", name = "first_name", @size = "60", @maxlength = "128", placeholder = "First Name", style = "background-image: url(&quot;data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAABHklEQVQ4EaVTO26DQBD1ohQWaS2lg9JybZ+AK7hNwx2oIoVf4UPQ0Lj1FdKktevIpel8AKNUkDcWMxpgSaIEaTVv3sx7uztiTdu2s/98DywOw3Dued4Who/M2aIx5lZV1aEsy0+qiwHELyi+Ytl0PQ69SxAxkWIA4RMRTdNsKE59juMcuZd6xIAFeZ6fGCdJ8kY4y7KAuTRNGd7jyEBXsdOPE3a0QGPsniOnnYMO67LgSQN9T41F2QGrQRRFCwyzoIF2qyBuKKbcOgPXdVeY9rMWgNsjf9ccYesJhk3f5dYT1HX9gR0LLQR30TnjkUEcx2uIuS4RnI+aj6sJR0AM8AaumPaM/rRehyWhXqbFAA9kh3/8/NvHxAYGAsZ/il8IalkCLBfNVAAAAABJRU5ErkJggg==&quot;); background-repeat: no-repeat; background-attachment: scroll; background-size: 16px 18px; background-position: 98% 50%; cursor: auto;" })
                                            <div class="description">First Name.</div>
                                        </div>
                                        <div class="form-item form-type-textfield form-item-last-name">
                                            <label class="element-invisible" for="edit-last-name">Last Name <span class="form-required" title="This field is required.">*</span></label>
                                            @Html.TextBoxFor(m => m.LastName, new { @class = "user-last-name form-text required", id = "edit-last-name", name = "last_name", @size = "60", @maxlength = "128", placeholder = "Last Name" })
                                            <div class="description">Last Name.</div>
                                        </div>
                                        <div class="form-item form-type-textfield form-item-email">
                                            <label class="element-invisible" for="edit-email--2">Email Address <span class="form-required" title="This field is required.">*</span></label>
                                            @Html.TextBoxFor(m => m.EmailAddress, new { @class = "user-email form-text required", id = "edit-email--2", name = "email", @size = "60", @maxlength = "128", placeholder = "Email Address" })
                                            <div class="description">Email Address.</div>
                                        </div>
                                        <div class="clip-card-container">
                                            <div class="form-item form-type-textfield form-item-clip-card-number">
                                                <label class="element-invisible" for="edit-clip-card-number">Clipper Card Number <span class="form-required" title="This field is required.">*</span></label>
                                                @Html.TextBoxFor(m => m.ClipperCardNumber, new { @class = "user-clip-num form-text required", id = "edit-clip-card-number", name = "clip_card_number", @size = "60", @maxlength = "128", placeholder = "Clipper Card Number" })
                                                <div class="description">Clipper Card Number.</div>
                                            </div>
                                            <div class="clip-card-img"><img src="~/Content/images/icon_clipperCard.png" alt="Clipper-Card"></div>
                                            <div class="form-item form-type-password-confirm form-item-password">
                                                <label class="element-invisible" for="edit-password--2">Password <span class="form-required" title="This field is required.">*</span></label>
                                                <div class="form-item form-type-password form-item-password-pass1">
                                                    <label class="element-invisible" for="edit-password-pass1">Password <span class="form-required" title="This field is required.">*</span></label>
                                                    @Html.TextBoxFor(m => m.Password, new { @class = "password-field form-text required", id = "edit-password-pass1", name = "password[pass1]", @size = "60", @maxlength = "128", placeholder = "Create Password", style = "background-image: url(&quot;data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAACIUlEQVQ4EX2TOYhTURSG87IMihDsjGghBhFBmHFDHLWwSqcikk4RRKJgk0KL7C8bMpWpZtIqNkEUl1ZCgs0wOo0SxiLMDApWlgOPrH7/5b2QkYwX7jvn/uc//zl3edZ4PPbNGvF4fC4ajR5VrNvt/mo0Gr1ZPOtfgWw2e9Lv9+chX7cs64CS4Oxg3o9GI7tUKv0Q5o1dAiTfCgQCLwnOkfQOu+oSLyJ2A783HA7vIPLGxX0TgVwud4HKn0nc7Pf7N6vV6oZHkkX8FPG3uMfgXC0Wi2vCg/poUKGGcagQI3k7k8mcp5slcGswGDwpl8tfwGJg3xB6Dvey8vz6oH4C3iXcFYjbwiDeo1KafafkC3NjK7iL5ESFGQEUF7Sg+ifZdDp9GnMF/KGmfBdT2HCwZ7TwtrBPC7rQaav6Iv48rqZwg+F+p8hOMBj0IbxfMdMBrW5pAVGV/ztINByENkU0t5BIJEKRSOQ3Aj+Z57iFs1R5NK3EQS6HQqF1zmQdzpFWq3W42WwOTAf1er1PF2USFlC+qxMvFAr3HcexWX+QX6lUvsKpkTyPSEXJkw6MQ4S38Ljdbi8rmM/nY+CvgNcQqdH6U/xrYK9t244jZv6ByUOSiDdIfgBZ12U6dHEHu9TpdIr8F0OP692CtzaW/a6y3y0Wx5kbFHvGuXzkgf0xhKnPzA4UTyaTB8Ph8AvcHi3fnsrZ7Wore02YViqVOrRXXPhfqP8j6MYlawoAAAAASUVORK5CYII=&quot;); background-repeat: no-repeat; background-attachment: scroll; background-size: 16px 18px; background-position: 98% 50%; cursor: auto;" })
                                                </div>
                                                <div class="form-item form-type-password form-item-password-pass2">
                                                    <label class="element-invisible" for="edit-password-pass2">Confirm password <span class="form-required" title="This field is required.">*</span></label>
                                                    @Html.TextBoxFor(m => m.PasswordConfirm, new { @class = "password-confirm form-text required", id = "edit-password-pass1", name = "password[pass2]", @size = "60", @maxlength = "128", placeholder = "Confirm Password", style = "background-image: url(&quot;data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAACIUlEQVQ4EX2TOYhTURSG87IMihDsjGghBhFBmHFDHLWwSqcikk4RRKJgk0KL7C8bMpWpZtIqNkEUl1ZCgs0wOo0SxiLMDApWlgOPrH7/5b2QkYwX7jvn/uc//zl3edZ4PPbNGvF4fC4ajR5VrNvt/mo0Gr1ZPOtfgWw2e9Lv9+chX7cs64CS4Oxg3o9GI7tUKv0Q5o1dAiTfCgQCLwnOkfQOu+oSLyJ2A783HA7vIPLGxX0TgVwud4HKn0nc7Pf7N6vV6oZHkkX8FPG3uMfgXC0Wi2vCg/poUKGGcagQI3k7k8mcp5slcGswGDwpl8tfwGJg3xB6Dvey8vz6oH4C3iXcFYjbwiDeo1KafafkC3NjK7iL5ESFGQEUF7Sg+ifZdDp9GnMF/KGmfBdT2HCwZ7TwtrBPC7rQaav6Iv48rqZwg+F+p8hOMBj0IbxfMdMBrW5pAVGV/ztINByENkU0t5BIJEKRSOQ3Aj+Z57iFs1R5NK3EQS6HQqF1zmQdzpFWq3W42WwOTAf1er1PF2USFlC+qxMvFAr3HcexWX+QX6lUvsKpkTyPSEXJkw6MQ4S38Ljdbi8rmM/nY+CvgNcQqdH6U/xrYK9t244jZv6ByUOSiDdIfgBZ12U6dHEHu9TpdIr8F0OP692CtzaW/a6y3y0Wx5kbFHvGuXzkgf0xhKnPzA4UTyaTB8Ph8AvcHi3fnsrZ7Wore02YViqVOrRXXPhfqP8j6MYlawoAAAAASUVORK5CYII=&quot;); background-repeat: no-repeat; background-attachment: scroll; background-size: 16px 18px; background-position: 98% 50%; cursor: auto;" })
                                                </div>
                                                <div class="description">Enter the same password in both fields.</div>
                                            </div>
                                            <input class="custom-form-submit cus-btn-disabled form-submit" type="submit" id="edit-submit--2" name="op" value="SIGN-UP" disabled="disabled">
                                            <div class="terms-condition">By clicking the Sign Up button, you agree to our <a href="/">Terms &amp; Conditions</a>, and <a href="/">Privacy Policy</a>.</div>
                                        </div>
                                    </div>
                                </div>
                            }
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

BARTPerks/Views/Perks/SignupComplete.cshtml
@model BARTPerks.Models.PerksModel

@{
    ViewBag.Title = "Signup Complete";
    ViewBag.BodyClasses = "page-gift-card page-gift-card-signup";
}

<div class="title-wrapper clearfix">
    <h1 class="title" id="page-title">@ViewBag.Title</h1>
</div>
<div class="region region-content">
    <div id="block-system-main" class="block block-system">
        <div class="content">
            <div class="signup-desc">
                <div class="success-status">
                    <p>Congratulations!</p>
                </div>
            </div>
        </div>
    </div>
</div>